# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cd257b20421111d636b06f68d607703bba26b352cd0477d802dacdc4e1f20b58a1d52bfd1fed2991b829065550e337c56e3865c0d3ca60ba8e4396d7dd538e0

test:
  secret_key_base: 392da0f21d56a448e1a3b1af8a8cd89c239e29a0feb83a108b97b4c105fabc8683153fb228cad4b236aae691f3534624e724054c113009da12cfe09bc71cf25a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
